### PR TITLE
Integrate AWS S3 storage

### PR DESCRIPTION
**Pull request by Ahmed-Emad**
Integrate AWS S3 storage

### CODE REVIEW

**Comment by friederbluemle** [comment]
Hi @Ahmed-Emad - This looks like a great feature to have. Was there a reason you closed the PR? Can we reopen it?

**Comment by Ahmed-Emad** [comment]
Sure, I have reopened it.

**Comment by friederbluemle** [comment]
Thank you! Do you think you can make the unit tests pass when you have some time available?

After briefly checking the code, it appears you would need `sinon.stub` to stub out the `S3` class, which you would then pass as a parameter to the `S3StoragePlugin` constructor. Something like this in your test file:

```
import { S3 } from "aws-sdk";

const stubs = {
  s3: sinon.stub(S3) as any,
};
```

Then instantiate the subject under test like this:

```
const sut = new S3StoragePlugin(storageConfig, {s3: stubs.s3});
```

You will require several more stubs to replace method calls etc. (Need to dig through the S3 sources, or get info from error stacktraces)
Check the `beforeEach` block in `AzureStoragePlugin.test.ts` for an example.

**Comment by Ahmed-Emad** [comment]
Fixed the unit tests.

**Comment by Ahmed-Emad** [comment]
I have just signed the CLA.

**Comment by friederbluemle** [comment]
Thanks a lot @Ahmed-Emad - Looks great, appreciate the contribution 👏

**Review by friederbluemle — APPROVED** [review]
👍

**Pull request merged**
